# ===== PROD =====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.batch.job.enabled=false

duckdb.path=${DUCKDB_PATH}

ai.server.base-url=${AI_SERVER_URL}
